export const ORDER_RULES = Object.freeze({
  MAX_POSSIBLE_ORDER: 20,
});

export const DECEMBER = Object.freeze({
  START_DATE: 1,
  END_DATE: 31,
  XMAS_DATE: 25,
  YEAR: 2023,
  MONTH: 12,
});

export const DISCOUNT = Object.freeze({
  XMAS_BASIC_DISCOUNT: 1000,
  DAYS_DISCOUNT: 2023,
  SPECIAL_DISCOUNT: 1000,
  COMPLIMENTARY_DISCOUNT: 25000,
  MIN_PRICE_FOR_COMPLIMENTARY: 120000,
});
